[phases.setup]
nixPkgs = ["python311", "python311Packages.pip", "python311Packages.setuptools"]

[phases.install]
cmds = [
    "python3 -m ensurepip --upgrade",
    "python3 -m pip install --upgrade pip",
    "python3 -m pip install -r backend/requirements.txt"
]

[start]
cmd = "cd backend && uvicorn app.main:app --host 0.0.0.0 --port $PORT" 