[build]
builder = "nixpacks"
buildCommand = "python3 -m pip install --upgrade pip && python3 -m pip install -r backend/requirements.txt"

[deploy]
startCommand = "cd backend && uvicorn app.main:app --host 0.0.0.0 --port $PORT"
healthcheckPath = "/health"
healthcheckTimeout = 100
restartPolicyType = "on_failure"

[env]
PYTHON_VERSION = "3.11"
NODE_VERSION = "16.x"

[nixpacks]
start-command = "cd backend && uvicorn app.main:app --host 0.0.0.0 --port $PORT" 