"""add_hero_events_and_hero_active

Revision ID: f8c86387de14
Revises: df2b60d4811c
Create Date: 2025-08-29 21:27:50.091110

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f8c86387de14'
down_revision: Union[str, None] = 'df2b60d4811c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # This migration is now redundant since the table and columns were created in the previous migration
    # Just ensure the foreign key constraint is properly set
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
