"""create_hero_events_table

Revision ID: df2b60d4811c
Revises: b7c91b70265f
Create Date: 2025-08-29 14:02:47.402658

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'df2b60d4811c'
down_revision: Union[str, None] = 'b7c91b70265f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hero_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('hero_image_url', sa.String(), nullable=False),
    sa.Column('order_position', sa.Integer(), nullable=False, server_default='0'),
    sa.Column('is_active', sa.Boolean(), nullable=False, server_default='true'),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_hero_events_active', 'hero_events', ['is_active'], unique=False)
    op.create_index('idx_hero_events_event_id', 'hero_events', ['event_id'], unique=False)
    op.create_index('idx_hero_events_order', 'hero_events', ['order_position'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_hero_events_order', table_name='hero_events')
    op.drop_index('idx_hero_events_event_id', table_name='hero_events')
    op.drop_index('idx_hero_events_active', table_name='hero_events')
    op.drop_table('hero_events')
    # ### end Alembic commands ###
