"""remove_time_column_from_event_requests

Revision ID: 50180583fe12
Revises: e079f732253d
Create Date: 2025-07-09 19:20:03.922347

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '50180583fe12'
down_revision: Union[str, None] = 'e079f732253d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('event_requests', 'time')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('event_requests', sa.Column('time', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
