"""add_venues_table

Revision ID: a2cc1a1071aa
Revises: 50180583fe12
Create Date: 2025-07-11 01:34:29.168232

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a2cc1a1071aa'
down_revision: Union[str, None] = '50180583fe12'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('venues', sa.Column('city', sa.String(), nullable=True))
    op.create_index(op.f('ix_venues_city'), 'venues', ['city'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_venues_city'), table_name='venues')
    op.drop_column('venues', 'city')
    # ### end Alembic commands ###
