"""add genre to event_requests

Revision ID: c2f2c9a042c1
Revises: ff38f22ee65b
Create Date: 2025-07-15 13:36:25.499793

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c2f2c9a042c1'
down_revision: Union[str, None] = 'ff38f22ee65b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('event_requests', sa.Column('genre', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('event_requests', 'genre')
    # ### end Alembic commands ###
