"""add_hero_events_and_hero_active

Revision ID: f8c86387de14
Revises: df2b60d4811c
Create Date: 2025-08-29 21:27:50.091110

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f8c86387de14'
down_revision: Union[str, None] = 'df2b60d4811c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('hero_events', 'order_position',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_index('idx_hero_events_active', table_name='hero_events')
    op.drop_index('idx_hero_events_event_id', table_name='hero_events')
    op.drop_index('idx_hero_events_order', table_name='hero_events')
    op.create_index(op.f('ix_hero_events_id'), 'hero_events', ['id'], unique=False)
    op.drop_constraint('hero_events_event_id_fkey', 'hero_events', type_='foreignkey')
    op.create_foreign_key(None, 'hero_events', 'events', ['event_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'hero_events', type_='foreignkey')
    op.create_foreign_key('hero_events_event_id_fkey', 'hero_events', 'events', ['event_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_hero_events_id'), table_name='hero_events')
    op.create_index('idx_hero_events_order', 'hero_events', ['order_position'], unique=False)
    op.create_index('idx_hero_events_event_id', 'hero_events', ['event_id'], unique=False)
    op.create_index('idx_hero_events_active', 'hero_events', ['is_active'], unique=False)
    op.alter_column('hero_events', 'order_position',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
