"""add date_types and ticket_price to event

Revision ID: 9f127cc95c19
Revises: 63d995bf0f41
Create Date: 2025-06-30 12:56:04.658056

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9f127cc95c19'
down_revision: Union[str, None] = '63d995bf0f41'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('date_types', postgresql.ARRAY(sa.String()), nullable=True))
    op.add_column('events', sa.Column('ticket_price', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('events', 'ticket_price')
    op.drop_column('events', 'date_types')
    # ### end Alembic commands ###
