"""change_time_field_to_string

Revision ID: e079f732253d
Revises: 86305875a5d4
Create Date: 2025-07-09 18:58:50.758069

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e079f732253d'
down_revision: Union[str, None] = '86305875a5d4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('event_requests', 'time',
               existing_type=postgresql.TIME(),
               type_=sa.String(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('event_requests', 'time',
               existing_type=sa.String(),
               type_=postgresql.TIME(),
               existing_nullable=True)
    # ### end Alembic commands ###
